### ISSUE TITLE
windows build

### ISSUE THREAD

**Issue by sec13b** [EvilBytecode/EDR-XDR-AV-Killer#2]
C:\Users\work\Desktop\BypassUAC\test\EDR-XDR-AV-Killer>"C:\Program Files\Go\bin\go.exe" build .
go: go.mod file not found in current directory or any parent directory; see 'go help modules'

C:\Users\work\Desktop\BypassUAC\test\EDR-XDR-AV-Killer>

**Comment by EvilBytecode** [comment]
go mod init wow
Do that cmd above
